const categories = {
  Protein: [
    { name: "Whey Protein", type: "Fast-absorbing", price_INR: 1500 },
    { name: "Casein Protein", type: "Slow-release", price_INR: 2000 },
    { name: "Pea Protein", type: "Plant-based", price_INR: 1800 },
    { name: "Rice Protein", type: "Plant-based", price_INR: 1700 },
    { name: "Hemp Protein", type: "Plant-based", price_INR: 1900 },
    { name: "Soy Protein", type: "Plant-based", price_INR: 1600 },
    { name: "Egg White Protein", type: "Animal-based", price_INR: 2200 },
    { name: "Milk Protein Isolate", type: "Dairy-based", price_INR: 2100 },
    { name: "Beef Protein", type: "Animal-based", price_INR: 2500 },
    { name: "Collagen Protein", type: "Specialized", price_INR: 2300 },
  ],
  AminoAcids: [
    { name: "BCAAs (Leucine)", type: "Amino Acid", price_INR: 1200 },
    { name: "BCAAs (Isoleucine)", type: "Amino Acid", price_INR: 1200 },
    { name: "BCAAs (Valine)", type: "Amino Acid", price_INR: 1200 },
    {
      name: "Essential Amino Acids (EAAs)",
      type: "Amino Acid",
      price_INR: 1500,
    },
    { name: "L-Glutamine", type: "Amino Acid", price_INR: 1000 },
    { name: "Arginine", type: "Amino Acid", price_INR: 1100 },
    { name: "Citrulline", type: "Amino Acid", price_INR: 1300 },
    { name: "Methionine", type: "Amino Acid", price_INR: 1400 },
    { name: "Histidine", type: "Amino Acid", price_INR: 1300 },
    { name: "Tyrosine", type: "Amino Acid", price_INR: 1100 },
  ],
  Creatine: [
    { name: "Creatine Monohydrate", type: "Creatine", price_INR: 800 },
    { name: "Creatine HCL", type: "Creatine", price_INR: 900 },
    { name: "Buffered Creatine", type: "Creatine", price_INR: 1000 },
    { name: "Micronized Creatine", type: "Creatine", price_INR: 850 },
    { name: "Creatine Ethyl Ester", type: "Creatine", price_INR: 950 },
    { name: "Kre-Alkalyn", type: "Creatine", price_INR: 1000 },
    { name: "Creatine Nitrate", type: "Creatine", price_INR: 1200 },
    { name: "Tri-Creatine Malate", type: "Creatine", price_INR: 1100 },
    { name: "Creatine Pyruvate", type: "Creatine", price_INR: 1300 },
    { name: "Liquid Creatine", type: "Creatine", price_INR: 1000 },
  ],
  PreWorkout: [
    { name: "Pre-Workout Blend 1", type: "Pre-Workout", price_INR: 1500 },
    { name: "Pre-Workout Blend 2", type: "Pre-Workout", price_INR: 1600 },
    { name: "Pre-Workout Blend 3", type: "Pre-Workout", price_INR: 1700 },
    { name: "Pre-Workout Blend 4", type: "Pre-Workout", price_INR: 1800 },
    { name: "Pre-Workout Blend 5", type: "Pre-Workout", price_INR: 1900 },
    { name: "Pre-Workout Blend 6", type: "Pre-Workout", price_INR: 2000 },
    { name: "Pre-Workout Blend 7", type: "Pre-Workout", price_INR: 2100 },
    { name: "Pre-Workout Blend 8", type: "Pre-Workout", price_INR: 2200 },
    { name: "Pre-Workout Blend 9", type: "Pre-Workout", price_INR: 2300 },
    { name: "Pre-Workout Blend 10", type: "Pre-Workout", price_INR: 2400 },
  ],
  "Omega-3FattyAcids": [
    { name: "Fish Oil Capsules 1", type: "Omega-3", price_INR: 800 },
    { name: "Fish Oil Capsules 2", type: "Omega-3", price_INR: 900 },
    { name: "Fish Oil Capsules 3", type: "Omega-3", price_INR: 1000 },
    { name: "Fish Oil Capsules 4", type: "Omega-3", price_INR: 1100 },
    { name: "Fish Oil Capsules 5", type: "Omega-3", price_INR: 1200 },
    { name: "Fish Oil Capsules 6", type: "Omega-3", price_INR: 1300 },
    { name: "Fish Oil Capsules 7", type: "Omega-3", price_INR: 1400 },
    { name: "Fish Oil Capsules 8", type: "Omega-3", price_INR: 1500 },
    { name: "Fish Oil Capsules 9", type: "Omega-3", price_INR: 1600 },
    { name: "Fish Oil Capsules 10", type: "Omega-3", price_INR: 1700 },
  ],
  VitaminsandMinerals: [
    { name: "Multivitamin 2", type: "Vitamin", price_INR: 700 },
    { name: "Multivitamin 3", type: "Vitamin", price_INR: 800 },
    { name: "Multivitamin 4", type: "Vitamin", price_INR: 900 },
    { name: "Multivitamin 5", type: "Vitamin", price_INR: 1000 },
    { name: "Multivitamin 6", type: "Vitamin", price_INR: 1100 },
    { name: "Multivitamin 7", type: "Vitamin", price_INR: 1200 },
    { name: "Multivitamin 8", type: "Vitamin", price_INR: 1300 },
    { name: "Multivitamin 9", type: "Vitamin", price_INR: 1400 },
    { name: "Multivitamin 10", type: "Vitamin", price_INR: 1500 },
  ],
  TestosteroneBoosters: [
    { name: "Zinc Supplement 1", type: "Mineral", price_INR: 500 },
    { name: "Zinc Supplement 2", type: "Mineral", price_INR: 550 },
    { name: "Zinc Supplement 3", type: "Mineral", price_INR: 600 },
    { name: "Zinc Supplement 4", type: "Mineral", price_INR: 650 },
    { name: "Magnesium Supplement 1", type: "Mineral", price_INR: 700 },
    { name: "Magnesium Supplement 2", type: "Mineral", price_INR: 750 },
    { name: "Magnesium Supplement 3", type: "Mineral", price_INR: 800 },
    { name: "Magnesium Supplement 4", type: "Mineral", price_INR: 850 },
    { name: "Vitamin D3 Supplement 1", type: "Vitamin", price_INR: 600 },
    { name: "Vitamin D3 Supplement 2", type: "Vitamin", price_INR: 650 },
  ],
  Miscellaneous: [
    { name: "Beta-Alanine", type: "Amino Acid", price_INR: 1200 },
    { name: "Glutamine", type: "Amino Acid", price_INR: 1000 },
    { name: "HMB", type: "Amino Acid", price_INR: 1500 },
    { name: "L-Carnitine", type: "Amino Acid", price_INR: 1300 },
    { name: "Taurine", type: "Amino Acid", price_INR: 1100 },
    { name: "Beta-Hydroxytryptophan", type: "Amino Acid", price_INR: 1400 },
    { name: "N-Acetyl Cysteine", type: "Amino Acid", price_INR: 1600 },
    {
      name: "CLA (Conjugated Linoleic Acid)",
      type: "Fatty Acid",
      price_INR: 1100,
    },
    { name: "Green Tea Extract", type: "Antioxidant", price_INR: 1200 },
    { name: "Turmeric Curcumin", type: "Anti-Inflammatory", price_INR: 1300 },
  ],
};

export default categories;
